# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from logic.proto import api_pb2 as logic_dot_proto_dot_api__pb2


class TagStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeObject = channel.unary_unary(
                '/main.Tag/RecognizeObject',
                request_serializer=logic_dot_proto_dot_api__pb2.RecognizeObjectRequest.SerializeToString,
                response_deserializer=logic_dot_proto_dot_api__pb2.RecognizeObjectResponse.FromString,
                )


class TagServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecognizeObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TagServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeObject': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeObject,
                    request_deserializer=logic_dot_proto_dot_api__pb2.RecognizeObjectRequest.FromString,
                    response_serializer=logic_dot_proto_dot_api__pb2.RecognizeObjectResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.Tag', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tag(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizeObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.Tag/RecognizeObject',
            logic_dot_proto_dot_api__pb2.RecognizeObjectRequest.SerializeToString,
            logic_dot_proto_dot_api__pb2.RecognizeObjectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
