# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logic/proto/api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='logic/proto/api.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15logic/proto/api.proto\x12\x04main\"\'\n\x16RecognizeObjectRequest\x12\r\n\x05photo\x18\x01 \x01(\x0c\"\'\n\x17RecognizeObjectResponse\x12\x0c\n\x04tags\x18\x01 \x01(\t2W\n\x03Tag\x12P\n\x0fRecognizeObject\x12\x1c.main.RecognizeObjectRequest\x1a\x1d.main.RecognizeObjectResponse\"\x00\x62\x06proto3'
)




_RECOGNIZEOBJECTREQUEST = _descriptor.Descriptor(
  name='RecognizeObjectRequest',
  full_name='main.RecognizeObjectRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='photo', full_name='main.RecognizeObjectRequest.photo', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=70,
)


_RECOGNIZEOBJECTRESPONSE = _descriptor.Descriptor(
  name='RecognizeObjectResponse',
  full_name='main.RecognizeObjectResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tags', full_name='main.RecognizeObjectResponse.tags', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['RecognizeObjectRequest'] = _RECOGNIZEOBJECTREQUEST
DESCRIPTOR.message_types_by_name['RecognizeObjectResponse'] = _RECOGNIZEOBJECTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecognizeObjectRequest = _reflection.GeneratedProtocolMessageType('RecognizeObjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZEOBJECTREQUEST,
  '__module__' : 'logic.proto.api_pb2'
  # @@protoc_insertion_point(class_scope:main.RecognizeObjectRequest)
  })
_sym_db.RegisterMessage(RecognizeObjectRequest)

RecognizeObjectResponse = _reflection.GeneratedProtocolMessageType('RecognizeObjectResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZEOBJECTRESPONSE,
  '__module__' : 'logic.proto.api_pb2'
  # @@protoc_insertion_point(class_scope:main.RecognizeObjectResponse)
  })
_sym_db.RegisterMessage(RecognizeObjectResponse)



_TAG = _descriptor.ServiceDescriptor(
  name='Tag',
  full_name='main.Tag',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=113,
  serialized_end=200,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecognizeObject',
    full_name='main.Tag.RecognizeObject',
    index=0,
    containing_service=None,
    input_type=_RECOGNIZEOBJECTREQUEST,
    output_type=_RECOGNIZEOBJECTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TAG)

DESCRIPTOR.services_by_name['Tag'] = _TAG

# @@protoc_insertion_point(module_scope)
